import 'package:abdoul_express/model/product.dart';
import 'package:abdoul_express/model/category.dart';
import 'package:abdoul_express/model/promotion.dart';

// Categories
const List<String> categories = [
  'Cosmétiques',
  'Sacs enfants',
  'Accessoires',
  'Électronique',
  'Mode',
  'Alimentation',
  'Maison',
  'Beauté',
  'Sports',
  'Livres',
];

final mockCategories = <Category>[
  Category(
    id: 'cat1',
    name: 'Cosmétiques',
    description: 'Découvrez notre sélection de produits de beauté et de maquillage pour sublimer votre routine quotidienne',
    productCount: 145,
    order: 1,
    createdAt: DateTime(2024, 1, 1),
    updatedAt: DateTime(2024, 1, 1),
    children: [
      Category(
        id: 'sub1-1',
        name: 'Maquillage',
        parentId: 'cat1',
        productCount: 78,
        order: 1,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub1-2',
        name: 'Soins de la peau',
        parentId: 'cat1',
        productCount: 45,
        order: 2,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub1-3',
        name: 'Accessoires beauté',
        parentId: 'cat1',
        productCount: 22,
        order: 3,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
    ],
  ),
  Category(
    id: 'cat2',
    name: 'Sacs enfants',
    description: 'Des sacs adorables et pratiques pour accompagner vos enfants dans leurs aventures scolaires',
    productCount: 89,
    order: 2,
    createdAt: DateTime(2024, 1, 1),
    updatedAt: DateTime(2024, 1, 1),
    children: [
      Category(
        id: 'sub2-1',
        name: 'Sacs à dos',
        parentId: 'cat2',
        productCount: 45,
        order: 1,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub2-2',
        name: 'Cartables',
        parentId: 'cat2',
        productCount: 32,
        order: 2,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub2-3',
        name: 'Trousses',
        parentId: 'cat2',
        productCount: 12,
        order: 3,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
    ],
  ),
  Category(
    id: 'cat3',
    name: 'Accessoires',
    description: 'Des pièces uniques pour compléter votre style et vous démarquer avec élégance',
    productCount: 234,
    order: 3,
    createdAt: DateTime(2024, 1, 1),
    updatedAt: DateTime(2024, 1, 1),
    children: [
      Category(
        id: 'sub3-1',
        name: 'Sacs',
        parentId: 'cat3',
        productCount: 98,
        order: 1,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub3-2',
        name: 'Bijoux',
        parentId: 'cat3',
        productCount: 76,
        order: 2,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub3-3',
        name: 'Lunettes',
        parentId: 'cat3',
        productCount: 34,
        order: 3,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub3-4',
        name: 'Autres',
        parentId: 'cat3',
        productCount: 26,
        order: 4,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
    ],
  ),
  Category(
    id: 'cat4',
    name: 'Électronique',
    description: 'Les dernières innovations technologiques pour simplifier votre quotidien',
    productCount: 512,
    order: 4,
    createdAt: DateTime(2024, 1, 1),
    updatedAt: DateTime(2024, 1, 1),
    children: [
      Category(
        id: 'sub4-1',
        name: 'Smartphones',
        parentId: 'cat4',
        productCount: 89,
        order: 1,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub4-2',
        name: 'Ordinateurs',
        parentId: 'cat4',
        productCount: 67,
        order: 2,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub4-3',
        name: 'Accessoires',
        parentId: 'cat4',
        productCount: 89,
        order: 3,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
    ],
  ),
  Category(
    id: 'cat5',
    name: 'Mode',
    description: 'Vêtements, chaussures et accessoires pour toute la famille',
    productCount: 512,
    order: 5,
    createdAt: DateTime(2024, 1, 1),
    updatedAt: DateTime(2024, 1, 1),
    children: [
      Category(
        id: 'sub5-1',
        name: 'Hommes',
        parentId: 'cat5',
        productCount: 201,
        order: 1,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub5-2',
        name: 'Femmes',
        parentId: 'cat5',
        productCount: 256,
        order: 2,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
      Category(
        id: 'sub5-3',
        name: 'Enfants',
        parentId: 'cat5',
        productCount: 55,
        order: 3,
        createdAt: DateTime(2024, 1, 1),
        updatedAt: DateTime(2024, 1, 1),
      ),
    ],
  ),
];

// Mock Promotions
final mockPromotions = <Promotion>[
  Promotion(
    id: '1',
    title: 'Vente Flash -50%',
    description: 'Sur une sélection d\'articles cosmétiques',
    imageAsset: 'assets/images/flash_sale.jpg',
    type: PromotionType.percentage,
    discountValue: 50,
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(hours: 24)),
    productIds: ['p1', 'p2', 'p9'],
    category: 'Cosmétiques',
  ),
  Promotion(
    id: '2',
    title: 'Livraison Gratuite',
    description: 'Pour toute commande supérieure à 10 000 F',
    imageAsset: 'assets/images/free_shipping.jpg',
    type: PromotionType.freeShipping,
    discountValue: 0,
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 7)),
    minimumOrder: 10000,
  ),
  Promotion(
    id: '3',
    title: '2ème article à -30%',
    description: 'Sur tous les accessoires de la collection',
    imageAsset: 'assets/images/buy_get_discount.jpg',
    type: PromotionType.percentage,
    discountValue: 30,
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 3)),
    category: 'Accessoires',
  ),
];

final mockProducts = <Product>[
  Product(
    id: 'p1',
    name: 'Coffret Cosmétiques',
    description: 'Un coffret minimal et chic pour un glow quotidien ✨',
    price: 3500,
    stock: 25,
    images: [
      'assets/images/cosmetics_set_minimal_studio_pink_1764505097880.jpg',
      'https://picsum.photos/seed/p1/600/600',
    ],
    categoryId: 'cat1',
    categoryName: 'Cosmétiques',
    rating: 4.7,
    reviewCount: 45,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 1),
    updatedAt: DateTime(2024, 1, 15),
  ),
  Product(
    id: 'p2',
    name: 'Rouge à lèvres',
    description: 'Pigment riche, fini soyeux, tenue longue durée 💄',
    price: 2500,
    stock: 100,
    images: [
      'assets/images/lipstick_minimal_product_photo_red_1764505098891.jpg',
      'https://picsum.photos/seed/p2/600/600',
    ],
    categoryId: 'cat1',
    categoryName: 'Cosmétiques',
    rating: 4.5,
    reviewCount: 89,
    featured: true,
    trending: true,
    isActive: true,
    createdAt: DateTime(2024, 1, 2),
    updatedAt: DateTime(2024, 1, 16),
  ),
  Product(
    id: 'p3',
    name: 'Sac à dos enfant',
    description: 'Pastel, léger et adorable pour l\'école 🎒',
    price: 4500,
    stock: 50,
    images: [
      'assets/images/kids_backpack_pastel_blue_1764505099679.jpg',
      'https://picsum.photos/seed/p3/600/600',
    ],
    categoryId: 'cat2',
    categoryName: 'Sacs enfants',
    rating: 4.6,
    reviewCount: 32,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 3),
    updatedAt: DateTime(2024, 1, 17),
  ),
  Product(
    id: 'p4',
    name: 'Cartable mignon',
    description: 'Compact et robuste pour les petites aventures 🐻',
    price: 2200,
    stock: 75,
    images: [
      'assets/images/children_school_bag_cute_yellow_1764505100614.jpg',
      'https://picsum.photos/seed/p4/600/600',
    ],
    categoryId: 'cat2',
    categoryName: 'Sacs enfants',
    rating: 4.3,
    reviewCount: 28,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 4),
    updatedAt: DateTime(2024, 1, 18),
  ),
  Product(
    id: 'p5',
    name: 'Chouchous doux',
    description: 'Lot de 3 chouchous en tissu premium 💜',
    price: 1500,
    stock: 200,
    images: [
      'assets/images/hair_accessories_scrunchies_lilac_1764505101426.jpg',
      'https://picsum.photos/seed/p5/600/600',
    ],
    categoryId: 'cat3',
    categoryName: 'Accessoires',
    rating: 4.8,
    reviewCount: 156,
    featured: true,
    trending: true,
    isActive: true,
    createdAt: DateTime(2024, 1, 5),
    updatedAt: DateTime(2024, 1, 19),
  ),
  Product(
    id: 'p6',
    name: 'Sac à main minimal',
    description: 'Design intemporel, lignes épurées et chic 👜',
    price: 4900,
    stock: 30,
    discount: 15.0,
    images: [
      'assets/images/women_handbag_modern_minimal_white_1764505102145.jpg',
      'https://picsum.photos/seed/p6/600/600',
    ],
    categoryId: 'cat3',
    categoryName: 'Accessoires',
    rating: 4.4,
    reviewCount: 67,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 6),
    updatedAt: DateTime(2024, 1, 20),
  ),
  Product(
    id: 'p7',
    name: 'Pinceaux maquillage',
    description: 'Fibre douce haute densité pour un finish pro 🖌️',
    price: 1900,
    stock: 80,
    images: [
      'assets/images/makeup_brush_set_brown_1764505103228.jpg',
      'https://picsum.photos/seed/p7/600/600',
    ],
    categoryId: 'cat1',
    categoryName: 'Cosmétiques',
    rating: 4.5,
    reviewCount: 92,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 7),
    updatedAt: DateTime(2024, 1, 21),
  ),
  Product(
    id: 'p8',
    name: 'Parfum minimal',
    description: 'Notes fraîches et subtiles en toute saison 🌿',
    price: 2500,
    stock: 45,
    images: [
      'assets/images/perfume_bottle_minimal_turquoise_1764505104098.jpg',
      'https://picsum.photos/seed/p8/600/600',
    ],
    categoryId: 'cat3',
    categoryName: 'Accessoires',
    rating: 4.2,
    reviewCount: 54,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 8),
    updatedAt: DateTime(2024, 1, 22),
  ),
  Product(
    id: 'p9',
    name: 'Crème hydratante',
    description: 'Hydratation 24h, peau douce et lumineuse 💧',
    price: 1750,
    stock: 120,
    discount: 10.0,
    images: [
      'assets/images/skincare_moisturizer_jar_green_1764505104973.jpg',
      'https://picsum.photos/seed/p9/600/600',
    ],
    categoryId: 'cat1',
    categoryName: 'Cosmétiques',
    rating: 4.6,
    reviewCount: 201,
    featured: true,
    trending: true,
    isActive: true,
    createdAt: DateTime(2024, 1, 9),
    updatedAt: DateTime(2024, 1, 23),
  ),
  Product(
    id: 'p10',
    name: 'Lunettes de soleil',
    description: 'Protection UV400 avec style minimal 😎',
    price: 2400,
    stock: 60,
    images: [
      'assets/images/sunglasses_modern_minimal_black_1764505105704.jpg',
      'https://picsum.photos/seed/p10/600/600',
    ],
    categoryId: 'cat3',
    categoryName: 'Accessoires',
    rating: 4.1,
    reviewCount: 38,
    featured: true,
    trending: false,
    isActive: true,
    createdAt: DateTime(2024, 1, 10),
    updatedAt: DateTime(2024, 1, 24),
  ),
];
