import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Initialize mock Hive for testing
/// Note: Adapters are generated by hive_generator and need to be registered
/// Run 'flutter packages pub run build_runner build' to generate adapters
Future<void> initMockHive() async {
  // Use in-memory storage for tests
  Hive.init('test');

  // Register adapters if they exist (generated by build_runner)
  // Uncomment these once adapters are generated:
  // if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(OrderStatusAdapter());
  // if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(OrderItemAdapter());
  // if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(OrderAdapter());
  // if (!Hive.isAdapterRegistered(14)) Hive.registerAdapter(AddressAdapter());
  // Add more adapters as needed
}

/// Close all Hive boxes
Future<void> closeMockHive() async {
  await Hive.close();
}

/// Clear all Hive boxes
Future<void> clearMockHive() async {
  await Hive.deleteFromDisk();
}

/// Delete specific box
Future<void> deleteBox(String boxName) async {
  await Hive.deleteBoxFromDisk(boxName);
}

/// Initialize mock SharedPreferences with default values
Future<void> initMockSharedPreferences([Map<String, Object>? values]) async {
  SharedPreferences.setMockInitialValues(values ?? {});
}

/// Get mock SharedPreferences instance
Future<SharedPreferences> getMockSharedPreferences() async {
  return await SharedPreferences.getInstance();
}

/// Clear all SharedPreferences data
Future<void> clearMockSharedPreferences() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.clear();
}
